name: Znueni
options:
  bundleIdPrefix: ch.emanuell
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "0.1.0"
targets:
  Znueni:
    type: application
    platform: iOS
    sources:
      - Znueni
    info:
      path: Znueni/Info.plist
      properties:
        CFBundleDisplayName: Znüni
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ch.emanuell.znueni
